global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ubuntu-vm1'
    static_configs:
      - targets: ['ubuntu-vm1:9100']

  - job_name: 'ubuntu-vm2'
    static_configs:
      - targets: ['ubuntu-vm2:9100']

rule_files:
  - /etc/prometheus/alert.rules.yml
