# Use the official Logstash image from Docker Hub
FROM logstash:7.17.9

# Copy your Logstash pipeline configuration
COPY logstash.conf /usr/share/logstash/pipeline/logstash.conf

# Expose the default Logstash port
EXPOSE 5044
