version: '3.8'

services:
  haproxy:
    build:
      context: ../../pools/haproxy
    container_name: haproxy
    ports:
      - '80:80'
    depends_on:
      - nginx-webserver1
      - nginx-webserver2
    networks:
      - haproxy-network

  nginx-webserver1:
    build:
      context: ../../pools/nginx-webserver/nginx-webserver1
    container_name: nginx-webserver1
    networks:
      - haproxy-network

  nginx-webserver2:
    build:
      context: ../../pools/nginx-webserver/nginx-webserver2
    container_name: nginx-webserver2
    networks:
      - haproxy-network

networks:
  haproxy-network:
    driver: bridge
